---
hostname: R9
mgmt: 10.0.0.209
interface: ge-0/0/0
loopback: 172.30.5.9
default-gateway: 10.0.0.1
units:
  - unit: 139
    vlan: 139
    neighbor: R3
    ip: 172.30.0.30
    mask: 30
  - unit: 149
    vlan: 149
    neighbor: R4
    ip: 172.30.0.38
    mask: 30
