groups {
    basic {
        system {
            host-name R7;
            root-authentication {
                encrypted-password "$1$vQqOn2iC$TlvjMurEPB9eo.O21zhn9/"; ## SECRET-DATA
            }
            login {
                user admin {
                    uid 2002;
                    class super-user;
                    authentication {
                        encrypted-password "$1$YCVjYya0$XCHE72IU.gSSkBaHHB8uS."; ## SECRET-DATA
                    }
                }
            }
            services {
                ssh;
                netconf {
                    ssh;
                }
            }
        }
        routing-options {
            router-id 172.30.5.7;
            forwarding-table {
                ecmp-fast-reroute;
            }
        }
    }
    OSPF {
            protocols {
                ospf {
                    traffic-engineering;
                    area 0.0.0.0 {
                    interface <ge-*> {
                        interface-type p2p;
                        link-protection;
                        ldp-synchronization;
                        bfd-liveness-detection {
                            minimum-interval 300;
                            multiplier 3;
                            }
                        }
                        interface em0.0 {
                            disable;
                        }
                        interface fxp0.0 {
                            disable;
                        }
                        interface lo0.0 {
                            passive;
                        }
                    }
                }
            }
        }
    }
apply-groups basic;
interfaces {
    ge-0/0/0 {
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
                unit 167 {
        description "HOST:R6|PORT:GE-0/0/0|UNIT:167"
            vlan-id 167;
            family inet {
                address 172.30.0.42/30;
            }
        }
                unit 127 {
        description "HOST:R2|PORT:GE-0/0/0|UNIT:127"
            vlan-id 127;
            family inet {
                address 172.30.0.18/30;
            }
        }
                unit 178 {
        description "HOST:R8|PORT:GE-0/0/0|UNIT:178"
            vlan-id 178;
            family inet {
                address 172.30.0.45/30;
            }
        }
                unit 710 {
        description "HOST:R10|PORT:GE-0/0/0|UNIT:710"
            vlan-id 710;
            family inet {
                address 172.30.0.81/30;
            }
        }
            }
    em0 {
        unit 0 {
            family inet {
                address 10.0.0.207/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 172.30.5.7/32;
            }
        }
    }
}
routing-options {
    static {
        route 0.0.0.0/0 next-hop 10.0.0.1;
    }
}
