---
# Verify NETCONF Connectivity
- name: Check NETCONF
  wait_for:
    host: "{{ansible_host}}"
    port: 830
    timeout: 10

# Create directory Render to render the configurations
- name: Create The Directory Render In Interfcae Configuraion Folder
  file:
    path: "{{playbook_dir}}/roles/interface-configuration/render"
    state: directory

# Render Initial Junos Configuration from Jinja2
- name: Include Device Interface variables
  include_vars:
    file: "{{playbook_dir}}/host_vars/{{ inventory_hostname }}/interface-config.yml"

# Render Initial Junos Configuration from Jinja2
- name: Render Initial Interface Configuration for Junos devices
  template:
    src: "templates/basic-connectivity.j2"
    dest: "{{playbook_dir}}/roles/interface-configuration/render/{{ inventory_hostname }}.basic.conf"

# Override Current Configuration with Rendered Configuration works with 14.1
- name: Deploy config to device ... please wait
  junos_config:
    src: "{{playbook_dir}}/roles/interface-configuration/render/{{ inventory_hostname }}.basic.conf"
    update: override
    comment: Applied by Ansible Override Basic Interface Configuration
    provider: "{{ credentials }}"


- name: collect default set of facts and configuration
  junos_facts:
    gather_subset: config
    config_format: text
    provider: "{{ credentials }}"
  register: "result_text"

# Create directory configurations to render the configurations
- name: Create The Directory Configuraion In Playbook Directory
  file:
    path: "{{playbook_dir}}/configurations/text"
    state: directory

- name: Copy Configuration in Configuration Text Directory
  copy:
    content: "{{ result_text.ansible_facts.ansible_net_config}}"
    dest: "{{ playbook_dir }}/configurations/text/{{ inventory_hostname }}_base.conf"


# Change the Description on Interfaces
#- name: Change description on interfaces based on a list of variable - Works with 14.1
#  junos_config:
#    lines:
#      - set interfaces ge-0/0/0 description "test 123"
#    comment: "Update description of interface "
#    provider: "{{ credentials }}"
