---
# Verify NETCONF Connectivity
- name: Check NETCONF
  wait_for:
    host: "{{ansible_host}}"
    port: 830
    timeout: 10

# Create directory Render to render the configurations
- name: Create The Directory Render In Interfcae Configuraion Folder
  file:
    path: "{{playbook_dir}}/roles/interface-configuration/render"
    state: directory

# Render Initial Junos Configuration from Jinja2
- name: Include Device Interface variables
  include_vars:
    file: "{{playbook_dir}}/host_vars/{{ inventory_hostname }}/interface-config.yml"

# Render Initial Junos Configuration from Jinja2
- name: Render Initial Interface Configuration for Junos devices
  template:
    src: "templates/basic-connectivity.j2"
    dest: "{{playbook_dir}}/roles/interface-configuration/render/{{ inventory_hostname }}.basic.conf"

# Install Rendered Configuration works with 14.1
- name: Deploy config to device ... please wait
  junos_config:
    src: "{{playbook_dir}}/roles/interface-configuration/render/{{ inventory_hostname }}.basic.conf"
    update: override
    comment: Applied by Ansible Override Basic Interface Configuration
    provider: "{{ credentials }}"

# Change the Description on Interfaces
#- name: Change description on interfaces based on a list of variable - Works with 14.1
#  junos_config:
#    lines:
#      - set interfaces ge-0/0/0 description "test 123"
#    comment: "Update description of interface "
#    provider: "{{ credentials }}"
