---
hostname: R6
mgmt: 10.0.0.206
interface: ge-0/0/0
loopback: 172.30.5.6
gateway: 10.0.0.1
units:
  - unit: 116
    vlan: 116
    neighbor: R1
    ip: 172.30.0.10
    mask: 30
  - unit: 156
    vlan: 156
    neighbor: R5
    ip: 172.30.0.46
    mask: 30
  - unit: 167
    vlan: 167
    neighbor: R7
    ip: 172.30.0.57
    mask: 30
areas:
  - area_id: 0.0.0.0
    interfaces:
      - ge-0/0/0.116
      - ge-0/0/0.156
  - area_id: 0.0.0.2
    interfaces:
      - ge-0/0/0.167
