---
hostname: R8
mgmt: 10.0.0.208
interface: ge-0/0/0
loopback: 172.30.5.8
gateway: 10.0.0.1
units:
  - unit: 148
    vlan: 148
    neighbor: R4
    ip: 172.30.0.42
    mask: 30
  - unit: 158
    vlan: 158
    neighbor: R5
    ip: 172.30.0.50
    mask: 30
  - unit: 810
    vlan: 810
    neighbor: R10
    ip: 172.30.0.65
    mask: 30
areas:
  - area_id: 0.0.0.1
    interfaces:
      - ge-0/0/0.148
      - ge-0/0/0.158
