---
hostname: R8
mgmt: 10.0.0.208
interface: ge-0/0/0
loopback: 172.30.5.8
units:
  - unit: 118
    vlan: 118
    neighbor: R1
    ip: 172.30.0.10
    mask: 30
  - unit: 138
    vlan: 138
    neighbor: R3
    ip: 172.30.0.54
    mask: 30
  - unit: 178
    vlan: 178
    neighbor: R7
    ip: 172.30.0.46
    mask: 30
  - unit: 810
    vlan: 810
    neighbor: R10
    ip: 172.30.0.86
    mask: 30
