---
hostname: R1
mgmt: 10.0.0.201
interface: ge-0/0/0
loopback: 172.30.5.1
gateway: 10.0.0.1
units:
  - unit: 112
    vlan: 112
    neighbor: R2
    ip: 172.30.0.1
    mask: 30
  - unit: 115
    vlan: 115
    neighbor: R5
    ip: 172.30.0.5
    mask: 30
  - unit: 116
    vlan: 116
    neighbor: R6
    ip: 172.30.0.9
    mask: 30
areas:
  - area_id: 0.0.0.0
    interfaces:
      - ge-0/0/0.112
      - ge-0/0/0.115
      - ge-0/0/0.116
