apply-groups [ basic OSPF ];
routing-options {

    router-id 172.30.5.1;
}
protocols {
    ospf {
          area 0.0.0.0 {
                interface ge-0/0/0.112;
                interface ge-0/0/0.115;
                interface ge-0/0/0.116;
                }
    }
}
