apply-groups [ basic OSPF ];
routing-options {

    router-id 172.30.5.4;
}
protocols {
    ospf {
          area 0.0.0.1 {
                interface ge-0/0/0.124;
                interface ge-0/0/0.134;
                interface ge-0/0/0.145;
                interface ge-0/0/0.148;
                }
          area 0.0.0.10 {
                interface ge-0/0/0.149;
                }
    }
}
