apply-groups [ basic OSPF ];
routing-options {

    router-id 172.30.5.3;
}
protocols {
    ospf {
          area 0.0.0.0 {
                interface ge-0/0/0.115;
                interface ge-0/0/0.156;
                }
          area 0.0.0.1 {
                interface ge-0/0/0.125;
                interface ge-0/0/0.145;
                interface ge-0/0/0.158;
                }
          area 0.0.0.2 {
                interface ge-0/0/0.157;
                }
    }
}
