apply-groups [ basic OSPF ];
routing-options {

    router-id 172.30.5.7;
}
protocols {
    ospf {
          area 0.0.0.2 {
                interface ge-0/0/0.157;
                interface ge-0/0/0.167;
                }
    }
}
