---
hostname: R5
mgmt: 10.0.0.205
interface: ge-0/0/0
loopback: 172.30.5.3
default-gateway: 10.0.0.1
units:
  - unit: 115
    vlan: 115
    neighbor: R1
    ip: 172.30.0.6
    mask: 30
  - unit: 125
    vlan: 125
    neighbor: R2
    ip: 172.30.0.22
    mask: 30
  - unit: 145
    vlan: 145
    neighbor: R4
    ip: 172.30.0.34
    mask: 30
  - unit: 156
    vlan: 156
    neighbor: R6
    ip: 172.30.0.45
    mask: 30
  - unit: 157
    vlan: 157
    neighbor: R7
    ip: 172.30.0.53
    mask: 30
  - unit: 158
    vlan: 158
    neighbor: R8
    ip: 172.30.0.49
    mask: 30
