name: On Pull Request Opened

on:
  pull_request:
    branches-ignore:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
      - review_request_removed
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR is approved
        id: check-approval
        run: |
          if [[ "${{ github.event.pull_request.state }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "Pull request is approved and merged."
          else
            echo "Pull request is not yet approved or merged. Skipping deployment."
            exit 1
          fi

      - name: Deploy to development environment
        if: github.event.pull_request.base.ref == 'development'
        run: |
          echo "Deploying to the development environment."
          # Add your deployment steps for development here.
          # Add your deployment commands here based on the environment url
